### ISSUE TITLE
Not Working - W7 x64

### ISSUE THREAD

**Issue by Combine12** [SM64-STROOP/STROOP#7]
I'm trying to use the tool with on Windows 7 64-bit and it doesn't seem to be working at all.

I've tried it with Mupen 0.5.1 and it does not display objects and seems to be reading the wrong values for  everything.

To clarify, I AM using a USA Super Mario 64 ROM.

**Comment by danebouchie** [comment]
Upon startup it should ask you to connect, do you at least get that message?

**Comment by danebouchie** [comment]
Mupen must be open before to see the connect mesaage, otherwise you need to click the dropdown at the top to select a specefic mupen program process

**Comment by danebouchie** [comment]
Mupen 0.5.1 is not initially supported at this time, but there is a partial workaround. This will at least fix the objects slots and other main functionality, but some of the variables will still remain incorrect. I recommended downloading Mupen 0.5.

There are future plans for getting Stroop to work with other emulators, however this remain at the lowest priorities before a final release.

**Partial Workaround:**
Go to Stroop's Config Folder (Stroop/Config), then open up Config.xml with a text editor (i.e. notepad). Look for this element on the 4th line down:

`<RAMStartAddress>0x008eba80</RAMStartAddress>`

Now replace 0x008eba80 with 0x008dcc00 for it to be:

`<RAMStartAddress>0x008dcc00</RAMStartAddress>`

**Comment by Combine12** [comment]
I have tried it on Mupen 0.5, but it still didn't work.

**Comment by danebouchie** [comment]
Sorry, to be clear what have you tried? What should ended up working is either:

 Performing the work around, running Mupen 0.5.1 (with all other versions of Mupen closed), then restarting Stroop. **Or** running Mupen 0.5, opening Stroop (without the workaround).

**Comment by Combine12** [comment]
I've tried it by running Mupen 0.5 and then running Stroop and it still shows wrong variables with no object display, for example Mario's position variables all display as 0 and his Yaw Velocity shows as 18068.

**Comment by danebouchie** [comment]
Where did you download mupen 0.5 from? Its probably an ambiguous version of mupen.

**Comment by Combine12** [comment]
Pretty sure I downloaded it from a post on "emutalk.net". I can't find it anywhere else. The Mupen 0.5 version listed on the emulation64 page for Mupen is for Linux and Mac only.

**Comment by danebouchie** [comment]
Actually, is it the re-recording version (can it record "movies")? That may or may not be the versioning difference. With that being said, try using [this version](http://adelikat.tasvideos.org/emulatordownloads/mupen64-rr/Mupen64%20v8%20installer.zip) off of [TASVideos](http://tasvideos.org/EmulatorResources/Mupen.html).

**Comment by Combine12** [comment]
That version seems to work perfectly fine.

**Comment by Combine12** [comment]
Seeing as that version of Mupen works, maybe it'd be wise to update the requirements?

**Comment by danebouchie** [comment]
Im still skeptical on which versions work. Can you answer my question on if the version thay didnt work was the rerecording version?

**Comment by Combine12** [comment]
No, It was not.

**Comment by danebouchie** [comment]
Im guessing thats probably what it is then. Ill update that requirement.

**Comment by xXvicente10Xx** [comment]
i am triying to play in mupen 1.0.10 but when i connect it with the mupen, doesnt work anything, then i try with mupen 0.5, also i try with run as admin and it doesnt work too, what i do?
