### ISSUE TITLE
"Map" not working

### ISSUE THREAD

**Issue by Arynn24** [SM64-STROOP/STROOP#8]
My version of Mupen64 is 0.5.1, and I can't open Map. It randomly crashes on me. Is there a way around this, or to fix it?

**Comment by danebouchie** [comment]
See [this issue](https://github.com/SM64-STROOP/STROOP/issues/7)

**Comment by danebouchie** [comment]
Also regarding the map not opening, you may have an old version of openGL. What version of windows are you running?

**Comment by Arynn24** [comment]
I am running Windows 10

**Comment by danebouchie** [comment]
So currently the map tab requires OpenGL 3.0 or greater (I update the requirements). See if you can figure out what version of OpenGL you have (based on your graphics card, or if you don't have one, your CPU).

**Comment by Arynn24** [comment]
I don't think I have one, do you have a download, or does it need a plugin chip?

**Comment by danebouchie** [comment]
Its a hardware requirement so you cant download it. You need the right type of computer. (Most ones around 2010 or newer I think) Ill see what I can do about lowering the opengl requirement in the future, but cant really do anything about it now. So sorry, but the Map tab is probably not going to work on that computer for now.

**Comment by Arynn24** [comment]
Ok, thank you!
